# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 17-Septiembre-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de 1 contenedor para el servicio de bolivariano
# -------------------------------------------------------------------

version: '3.7'
services:
  bolivariano-service:
    image: wortiz1027/bolivariano-services:latest
    container_name: bolivariano-service
    hostname: bolivariano-service
    restart: always
    ports:
      - 7071:7071
    networks:
      - ntw_backend
    environment:
      - SERVICE_PORTS=7071

networks:
  ntw_backend:
    external: true
